#!/bin/sh

dirname=`dirname $0`
tmp="${dirname#?}"

if [ "${dirname%$tmp}" != "/" ]; then
  dirname=$PWD/$dirname
fi
# LD_LIBRARY_PATH=$dirname/lib/nootka:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH
# unset QT_QPA_PLATFORM
$dirname/bin/nootka "$@" 
