name:     Installer

on:
  push:
    push:
      branches:
        - master

jobs:
  win_installer:
    name:           Build Windows installer
    runs-on:        windows-latest
    #if: "contains(github.event.commits[0].message, 'get_installer')"

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set variables
        run: |
          echo ("NOOTKA_VERSION=" + $((Get-Content .\src\libs\core\nootkaconfig.h | %{ $_.Split(' ')[2]; }) -replace '"', '')) >> $env:GITHUB_ENV
          echo ("NOOTKA_COM_CNT=" + $(git rev-list HEAD --count)) >> $env:GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_mingw81'
          tools: 'tools_mingw,8.1.0-1-202004170606,qt.tools.win32_mingw810'

      - name: Qt 5 environment configuration
        shell: pwsh
        run: |
          Write-Output "${{ env.Qt5_DIR }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          Write-Output "${{ env.IQTA_TOOLS }}/mingw810_32/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Compile and prepare installer
        shell: pwsh
        run: |
          ./packaging/nsis/build_installer.ps1

      - name: Upload installer to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: Nootka-Installer.exe #Nootka-${{ env.NOOTKA_VERSION }}-b${{ env.NOOTKA_COM_CNT }}.exe
          path: /Users/runner/work/nootka/nootka/Nootka-Installer.exe #Nootka-${{ env.NOOTKA_VERSION }}-b${{ env.NOOTKA_COM_CNT }}.exe


  upload_package:
    name:           Uploading to SF
    runs-on:        ubuntu-latest
    needs:          win_installer

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set variables
        run: |
          VER=$(cat src/libs/core/nootkaconfig.h | awk -F" " '{ print $3 }' | sed 's/\"//g')
          echo "NOOTKA_VERSION=$VER" >> $GITHUB_ENV
          CNT=$(git rev-list HEAD --count)
          echo "NOOTKA_COM_CNT=$CNT" >> $GITHUB_ENV

      - name: get artifacts
        uses: actions/download-artifact@v2
        with:
          name: Nootka-Installer.exe # Nootka-${{ env.NOOTKA_VERSION }}-b${{ env.NOOTKA_COM_CNT }}.exe

      - name: Upload installer to SF
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -avzr --delete
          path: Nootka-Installer.exe # Nootka-${{ env.NOOTKA_VERSION }}-b${{ env.NOOTKA_COM_CNT }}.exe
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.SSH_HOST  }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
