name:     Packaging

on:
  push:
    push:
      #tags:
        #- "v*"
      branches:
        - master

jobs:
  macos_dmg:
    name:           Build Mac dmg
    runs-on:        macos-latest
    if: "contains(github.event.commits[0].message, 'get_bundle')"

    steps:
      - name: Select Xcode version for Mac
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set variables
        run: |
          VER=$(cat src/libs/core/nootkaconfig.h | awk -F" " '{ print $3 }' | sed 's/\"//g')
          echo "NOOTKA_VERSION=$VER" >> $GITHUB_ENV
          CNT=$(git rev-list HEAD --count)
          echo "NOOTKA_COM_CNT=$CNT" >> $GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install fftw, sound-touch, ogg-vorbis
        run: |
          #brew update
          brew install fftw
          brew install sound-touch
          brew install libogg
          brew install libvorbis
          #brew upgrade

      - name: Compile and prepare dmg
        run: |
          echo "version is ${{ env.NOOTKA_VERSION }}"
          echo "commits number is ${{ env.NOOTKA_COM_CNT }}"
          mkdir build
          cd ./build
          mkdir installs
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installs ../
          make -j 2
          make install
          make deploy
          make dmg
          cp installs/Nootka*.dmg ../
          cd ..
          mv Nootka*.dmg Nootka-${{ env.NOOTKA_VERSION }}-b${{ env.NOOTKA_COM_CNT }}.dmg

      - name: Upload dmg to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: Nootka-${{ env.NOOTKA_VERSION }}-b${{ env.NOOTKA_COM_CNT }}.dmg
          path: /Users/runner/work/nootka/nootka/Nootka-${{ env.NOOTKA_VERSION }}-b${{ env.NOOTKA_COM_CNT }}.dmg


  upload_package:
    name:           Uploading to SF
    runs-on:        ubuntu-latest
    needs:          macos_dmg

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set variables
        run: |
          VER=$(cat src/libs/core/nootkaconfig.h | awk -F" " '{ print $3 }' | sed 's/\"//g')
          echo "NOOTKA_VERSION=$VER" >> $GITHUB_ENV
          CNT=$(git rev-list HEAD --count)
          echo "NOOTKA_COM_CNT=$CNT" >> $GITHUB_ENV

      - name: get artifacts
        uses: actions/download-artifact@v2
        with:
          name: Nootka-${{ env.NOOTKA_VERSION }}-b${{ env.NOOTKA_COM_CNT }}.dmg

      - name: Upload dmg to SF
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -avzr --delete
          path: /Users/runner/work/nootka/nootka/Nootka-${{ env.NOOTKA_VERSION }}-b${{ env.NOOTKA_COM_CNT }}.dmg
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.SSH_HOST  }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
